// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mniiolnjrbzdtqnofswm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uaWlvbG5qcmJ6ZHRxbm9mc3dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNDYyNDIsImV4cCI6MjA2NTkyMjI0Mn0.Eoyn_ohOwcq6GpkeIsH1iwu4GBiCmFEaYGLPVkXWnFY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);